import {cpSync,copyFileSync,mkdirSync,rmSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root = path.dirname(fileURLToPath(import.meta.url));
const output = path.join(root,'dist');
if (path.dirname(output) !== root || path.basename(output) !== 'dist') throw new Error('Invalid generated output path');
rmSync(output,{recursive:true,force:true});
mkdirSync(output,{recursive:true});
mkdirSync(path.join(output,'assets'),{recursive:true});
for (const file of ['index.html','style.css','app.js']) copyFileSync(path.join(root,file),path.join(output,file));
for (const file of ['favicon.svg','inter-variable.woff2']) copyFileSync(path.join(root,'assets',file),path.join(output,'assets',file));
cpSync(path.join(root,'vendor'),path.join(output,'vendor'),{recursive:true});
const guide = path.resolve(root,'../atlas-docs-site');
mkdirSync(path.join(output,'guide'),{recursive:true});
for(const file of ['index.html','app.js','content.js','data.js','icons.js','product-shot.js','site-shell.js']) copyFileSync(path.join(guide,file),path.join(output,'guide',file));
cpSync(path.join(guide,'styles'),path.join(output,'guide/styles'),{recursive:true});
mkdirSync(path.join(output,'guide/assets'),{recursive:true});
for(const file of ['favicon.svg','inter-variable.woff2']) copyFileSync(path.join(guide,'assets',file),path.join(output,'guide/assets',file));
cpSync(path.join(guide,'assets/product'),path.join(output,'guide/assets/product'),{recursive:true});
cpSync(path.join(guide,'composer'),path.join(output,'guide/composer'),{recursive:true});
console.log('Built standalone static website and /guide/ at',output);
