import { _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const output = path.join(root,'test-results'); fs.mkdirSync(output,{recursive:true});
const data = fs.mkdtempSync(path.join(os.tmpdir(),'execution-trainer-desktop-'));
const env = {...process.env, EXECUTION_TRAINER_DATA:data}; delete env.ELECTRON_RUN_AS_NODE;
let app;
const errors=[];
async function shot(page, options) {
  await page.evaluate(async () => { await Promise.all(document.getAnimations().map(animation => animation.finished.catch(() => {}))); });
  return page.screenshot(options);
}
async function launch() {
  app = await electron.launch({args:[root],env});
  const page = await app.firstWindow();
  page.on('pageerror', error => errors.push(error.message));
  await page.locator('#new, #complete').first().waitFor();
  return page;
}
try {
  let page=await launch();
  await shot(page, {path:path.join(output,'01-empty.png')});
  await page.locator('#new').click();
  await page.getByRole('button',{name:'创建训练',exact:true}).click();
  assert.equal(await page.locator('#name').getAttribute('aria-invalid'),'true');
  assert.equal(await page.locator('#name').evaluate(el=>el===document.activeElement),true);
  await shot(page, {path:path.join(output,'02-validation.png')});
  await page.locator('#name').fill('复盘');
  await page.locator('#target').fill('3');
  await page.locator('#daily').fill('2');
  await page.getByRole('button',{name:'创建训练',exact:true}).click();
  await page.locator('#complete').waitFor();
  await page.locator('#complete').click();
  await page.waitForFunction(()=>document.querySelector('.counter')?.textContent.trim()==='1 / 3');
  await shot(page, {path:path.join(output,'03-progress.png')});
  await app.close();
  page=await launch();
  assert.equal((await page.locator('.counter').textContent()).trim(),'1 / 3');
  await page.locator('#complete').click();
  await page.waitForFunction(()=>document.querySelector('.counter')?.textContent.trim()==='2 / 3');
  await page.locator('#complete').click();
  await page.getByRole('button',{name:'全部完成'}).waitFor();
  assert.equal(await page.locator('#complete').isDisabled(),true);
  await page.locator('#history > summary').click();
  await shot(page, {path:path.join(output,'04-complete.png')});
  await page.locator('#back').click();
  await page.locator('#new').click();
  await page.locator('#name').fill('每天完成一次专注的英语听力练习并核对原文中的发音与语调，不跳过任何已经承诺的练习');
  await page.getByRole('button',{name:'创建训练',exact:true}).click();
  await page.locator('#complete').waitFor();
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(380,440));
  await shot(page, {path:path.join(output,'05-small-long-title.png')});
  const geometry=await page.evaluate(()=>{
    const css=el=>{const s=getComputedStyle(el);const r=el.getBoundingClientRect();return {width:r.width,height:r.height,font:s.fontFamily,fontSize:s.fontSize,lineHeight:s.lineHeight,weight:s.fontWeight,color:s.color,background:s.backgroundColor};};
    return {viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},overflow:document.documentElement.scrollWidth>innerWidth,title:css(document.querySelector('h1')),button:css(document.querySelector('#complete')),counter:css(document.querySelector('.counter')),fontLoaded:document.fonts.check('13px "Inter Variable"')};
  });
  assert.equal(geometry.overflow,false);
  assert.ok(Math.abs(geometry.button.height - 36) < 0.1);
  assert.equal(geometry.title.fontSize,'20px');
  assert.equal(geometry.fontLoaded,true);
  await page.locator('#complete').focus();
  await page.keyboard.press('Space');
  await page.waitForFunction(()=>document.querySelector('.counter')?.textContent.trim()==='1 / 100');
  // Exercise a real publication failure without touching any user records.
  const recordDir=path.join(data,'records');
  const files=fs.readdirSync(recordDir).filter(n=>n.endsWith('.json'));
  const blocked=path.join(recordDir,`${String(files.length+1).padStart(10,'0')}.json`);
  fs.mkdirSync(blocked);
  await page.locator('#complete').click();
  await page.locator('#error').waitFor({state:'visible'});
  assert.equal((await page.locator('.counter').textContent()).trim(),'1 / 100');
  await shot(page, {path:path.join(output,'06-write-error.png')});
  fs.rmdirSync(blocked);
  await page.locator('#complete').click();
  await page.waitForFunction(()=>document.querySelector('.counter')?.textContent.trim()==='2 / 100');
  await page.locator('#history > summary').click();
  await page.evaluate(async () => { await Promise.all(document.getAnimations().map(a => a.finished.catch(() => {}))); });
  await page.locator('#complete').click();
  await page.waitForFunction(()=>document.querySelector('.counter')?.textContent.trim()==='3 / 100');
  assert.equal(await page.locator('#history').getAttribute('open'), '');
  const motionEvidence = await page.evaluate(() => document.getAnimations().map(a => ({duration:a.effect.getTiming().duration,frames:a.effect.getKeyframes()})));
  assert.ok(motionEvidence.some(a => a.duration === 220));
  fs.writeFileSync(path.join(output,'motion.json'),JSON.stringify(motionEvidence,null,2));
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.locator('#complete').click();
  await page.waitForFunction(()=>document.querySelector('.counter')?.textContent.trim()==='4 / 100');
  assert.equal(await page.evaluate(()=>document.getAnimations().length),0);
  await shot(page,{path:path.join(output,'07-reduced-motion.png')});
  await page.locator('#complete').dblclick();
  await page.waitForFunction(()=>document.querySelector('.counter')?.textContent.trim()==='6 / 100');
  const buttonBox=await page.locator('#complete').boundingBox();
  await page.mouse.click(buttonBox.x+buttonBox.width/2,buttonBox.y+buttonBox.height/2,{clickCount:10,delay:0});
  await page.waitForFunction(()=>document.querySelector('.counter')?.textContent.trim()==='16 / 100',null,{timeout:5000});
  const persisted = JSON.parse(fs.readFileSync(path.join(data,'records',fs.readdirSync(path.join(data,'records')).filter(n=>n.endsWith('.json')).sort().at(-1)),'utf8'));
  assert.equal(persisted.type,'complete');
  await page.locator('#minimize').click();
  assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isMinimized()),true);
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].restore());
  await shot(page,{path:path.join(output,'08-window-controls.png')});
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(output,'verification.json'),JSON.stringify({data,geometry,errors,result:'passed'},null,2));
  console.log(JSON.stringify({result:'passed',data,geometry,output}));
} finally { await app?.close(); }
