import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import { pathToFileURL } from 'node:url'
import { build } from 'vite'
import initSqlJs from 'sql.js'
import { chromium } from 'playwright'
const out=path.resolve('test-results/atlas-data-editor')
await fs.mkdir(out,{recursive:true})
await build({configFile:false,resolve:{alias:{'@':path.resolve('src')}},build:{outDir:out,emptyOutDir:false,lib:{entry:path.resolve('tools/atlas-data-editor/core.ts'),formats:['es'],fileName:()=> 'core.mjs'}}})
const {decode,validate,migrateToPaper,resetLive,SCHEMA_VERSION}=await import(pathToFileURL(path.join(out,'core.mjs')))
const SQL=await initSqlJs()
// Explicit read-only input. Tests never write under this directory.
const sourcePath=process.env.ATLAS_EDITOR_TEST_LIBRARY??'D:/YunkooTradelog'
const original=await fs.readFile(path.join(sourcePath,'journal.db'))
const db=new SQL.Database(original)
const meta=Object.fromEntries(db.exec('SELECT key,value FROM meta')[0].values)
const snapshot=decode(JSON.parse(meta.snapshot),Number(meta.schemaVersion))
validate(snapshot)
assert.throws(()=>decode(snapshot,SCHEMA_VERSION+1))
const selected=new Set(snapshot.trades.filter(t=>t.tradeKind!=='paper').map(t=>t.id))
const migrated=migrateToPaper(snapshot,selected)
assert.equal(migrated.trades.filter(t=>t.tradeKind!=='paper').length,0)
assert.deepEqual(migrated.trades.map(t=>t.note),snapshot.trades.map(t=>t.note))
assert.deepEqual(migrated.tagPresets,snapshot.tagPresets)
assert(migrated.trades.every(t=>!('liveStageId' in t)))
const reset=resetLive(migrated);validate(reset)
assert.equal(reset.weeklyReviews.length,0);assert.equal(reset.liveStages.length,1)
assert.throws(()=>resetLive(snapshot))
const liveOnlyMigrated=migrateToPaper(snapshot,new Set(snapshot.trades.filter(t=>t.tradeKind==='live').map(t=>t.id)))
const casePreservingReset=resetLive(liveOnlyMigrated)
validate(casePreservingReset)
assert.deepEqual(casePreservingReset.trades.filter(t=>t.tradeKind==='case'), snapshot.trades.filter(t=>t.tradeKind==='case').map(t=>({...t,liveStageId:null})))
assert.deepEqual(casePreservingReset.trades.filter(t=>t.tradeKind==='paper'), liveOnlyMigrated.trades.filter(t=>t.tradeKind==='paper'))
assert.deepEqual(casePreservingReset.tagPresets,snapshot.tagPresets)
assert.deepEqual(casePreservingReset.quickNotes,snapshot.quickNotes)
assert.deepEqual(casePreservingReset.strategies,snapshot.strategies)
assert.throws(()=>validate({...snapshot,currentLiveStageId:'missing'}))
db.close()
// Synthetic export fixture, retaining actual field shapes but replacing image bytes.
const fixture=JSON.parse(JSON.stringify(snapshot).replace(/journal-asset:\/\/[^"'\s<>\\]+/g,'journal-asset://fixture'))
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jWZkAAAAASUVORK5CYII=','base64')
const fdb=new SQL.Database();fdb.run('CREATE TABLE meta(key TEXT PRIMARY KEY,value TEXT);CREATE TABLE assets(id TEXT PRIMARY KEY,mime TEXT,file_name TEXT,byte_size INTEGER,created_at TEXT);')
for(const [k,v]of Object.entries({schemaVersion:String(SCHEMA_VERSION),snapshot:JSON.stringify(fixture)}))fdb.run('INSERT INTO meta VALUES (?,?)',[k,v])
fdb.run('INSERT INTO assets VALUES (?,?,?,?,?)',['fixture','image/png','fixture.png',png.length,new Date().toISOString()])
const files={'journal.db':Array.from(fdb.export()),'manifest.json':Array.from(Buffer.from(JSON.stringify({schemaVersion:SCHEMA_VERSION}))), 'attachments/fixture.png':Array.from(png)};fdb.close()
const browser=await chromium.launch({headless:true})
try{
 const page=await browser.newPage({viewport:{width:1500,height:960}});const errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.addInitScript(({files})=>{
  const sourceFiles=new Map(Object.entries(files).map(([k,v])=>[k,new Uint8Array(v)])),output=new Map();window.testOutput=output;window.testSource=sourceFiles
  function handle(map,prefix='',readOnly=false){return {name:readOnly?'测试源资料库':'测试输出',kind:'directory',async isSameEntry(other){return other._map===map&&other._prefix===prefix},_map:map,_prefix:prefix,async resolve(other){return other._map===map?[]:null},async *values(){for(const key of map.keys())yield {name:key}},async getDirectoryHandle(name){return handle(map,prefix+name+'/',readOnly)},async getFileHandle(name,{create=false}={}){const key=prefix+name;if(create&&readOnly)throw Error('Forbidden source write');if(!map.has(key)&&!create)throw Error('Missing '+key);return {async getFile(){return new File([map.get(key)],name)},async createWritable(){if(readOnly)throw Error('Forbidden source write');let bytes;return {async write(value){if(window.testFailCopy && key.startsWith('attachments/'))throw Error('模拟附件写入失败');bytes=value instanceof Blob?new Uint8Array(await value.arrayBuffer()):typeof value==='string'?new TextEncoder().encode(value):new Uint8Array(value)},async close(){map.set(key,bytes)},async abort(){}}}}}}}
  let calls=0;window.showDirectoryPicker=async()=>++calls===1?handle(sourceFiles,'',true):handle(output)
 },{files})
 await page.goto(pathToFileURL(path.resolve('release/atlas-data-editor/index.html')).href)
 await page.locator('#open').click();await page.waitForFunction(()=>document.querySelector('#source').textContent.includes('测试源'))
 await page.locator('#check').click();await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('校验通过'))
 await page.evaluate(()=>{window.testAsset=window.testSource.get('attachments/fixture.png');window.testSource.delete('attachments/fixture.png')})
 await page.locator('#check').click();await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('Missing attachments/fixture.png'))
 await page.evaluate(()=>window.testSource.set('attachments/fixture.png',window.testAsset))
 await page.getByRole('button',{name:'全选',exact:true}).click()
 assert.equal(await page.locator('tbody input:checked').count(),fixture.trades.filter(t=>t.tradeKind==='live').length)
 await page.getByRole('button',{name:'取消全选',exact:true}).click();assert.equal(await page.locator('tbody input:checked').count(),0)
 await page.getByLabel('按策略筛选').selectOption(fixture.trades.find(t=>t.tradeKind==='live').strategyId)
 const filteredCount=await page.locator('tbody tr').count()
 await page.getByLabel('全选当前结果',{exact:true}).check();assert.equal(await page.locator('tbody input:checked').count(),filteredCount)
 await page.getByLabel('全选当前结果',{exact:true}).uncheck();assert.equal(await page.locator('tbody input:checked').count(),0)
 await page.getByLabel('按策略筛选').selectOption('')
 await page.getByRole('button',{name:'全选',exact:true}).click()
 const targetStrategy=fixture.strategies.at(-1).id
 await page.getByLabel('批量设置策略',{exact:true}).selectOption(targetStrategy)
 await page.getByRole('button',{name:'批量设置策略',exact:true}).click()
 await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('条记录设置策略'))
 await page.locator('tbody tr').first().click();assert.equal(await page.getByLabel('交易策略',{exact:true}).inputValue(),targetStrategy)
 await page.locator('#undo').click();await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('已撤销'))
 await page.getByRole('button',{name:'全选',exact:true}).click();await page.getByRole('button',{name:'迁入模拟盘',exact:true}).click();await page.locator('#confirm').click();await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('已迁入模拟盘'))
 await page.locator('#undo').click();await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('已撤销'))
 await page.locator('tbody tr').first().click();await page.locator('textarea').fill('{bad json');await page.getByRole('button',{name:'应用编辑',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#open').disabled);assert.equal(await page.locator('textarea').inputValue(),'{bad json')
 await page.locator('#nav button').filter({hasText:'随记'}).click();await page.locator('#confirm').click()
 for(const label of ['标签预置','错误标签预置']){
   await page.locator('#nav button').filter({hasText:new RegExp('^'+label)}).click()
   await page.getByLabel('新增标签名称').fill('编辑器新增测试，编辑器新增测试')
   await page.getByRole('button',{name:'新增标签',exact:true}).click()
   await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('已新增标签预置'))
   assert.equal(await page.locator('tbody tr').filter({hasText:'编辑器新增测试'}).count(),1)
   await page.getByLabel('新增标签名称').fill('编辑器新增测试')
   await page.getByRole('button',{name:'新增标签',exact:true}).click()
   await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('已经存在'))
 }
 await page.locator('#nav button').filter({hasText:/^实盘日志/}).click()
 await page.getByRole('button',{name:'全选',exact:true}).click()
 await page.getByRole('button',{name:'迁入模拟盘',exact:true}).click();await page.locator('#confirm').click()
 await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('已迁入模拟盘'))
 await page.locator('#nav button').filter({hasText:/^实盘阶段/}).click()
 await page.getByRole('button',{name:'重新开始实盘',exact:true}).click();await page.locator('#confirm').click()
 await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('已重置实盘阶段'))
 await page.screenshot({path:path.join(out,'editor.png'),fullPage:true})
 await page.evaluate(()=>{const bytes=window.testSource.get('journal.db').slice();bytes[24]^=1;window.testSource.set('journal.db',bytes)})
 await page.locator('#export').click();await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('导出完成：'))
 await page.locator('#export').click();await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('导出目录必须为空'))
 const result=await page.evaluate(()=>Object.fromEntries([...window.testOutput].map(([k,v])=>[k,Array.from(v)])))
 for(const [key,bytes]of Object.entries(result)){const target=path.join(out,'export',key);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,new Uint8Array(bytes))}
 const reopened=new SQL.Database(new Uint8Array(result['journal.db']));validate(decode(JSON.parse(reopened.exec("SELECT value FROM meta WHERE key='snapshot'")[0].values[0][0]),SCHEMA_VERSION));reopened.close()
 assert.deepEqual(Buffer.from(result['attachments/fixture.png']),png)
 await build({configFile:false,resolve:{alias:{'@':path.resolve('src')}},build:{ssr:path.resolve('electron/library/storage.ts'),outDir:path.join(out,'desktop-reader'),emptyOutDir:false,rollupOptions:{output:{entryFileNames:'storage.mjs'}}}})
 const {LibraryStorage}=await import(pathToFileURL(path.join(out,'desktop-reader/storage.mjs')))
 const desktop=new LibraryStorage(path.join(out,'export'),{allowCreate:false})
 try{
   await desktop.open();const loaded=desktop.loadSnapshot()
   assert.equal(loaded.trades.length,snapshot.trades.length)
   assert.equal(loaded.trades.filter(t=>t.tradeKind==='live').length,0)
   assert.deepEqual(JSON.parse(JSON.stringify(loaded.trades.filter(t=>t.tradeKind==='case'))),fixture.trades.filter(t=>t.tradeKind==='case').map(t=>({...t,liveStageId:null})))
 }finally{desktop.close()}
 await page.evaluate(()=>{window.testOutput.clear();window.testFailCopy=true})
 await page.locator('#export').click();await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('导出未完成'))
 const failed=await page.evaluate(()=>({db:window.testOutput.has('journal.db'),state:window.testOutput.has('editor-export-state.json'),manifest:window.testOutput.has('manifest.json')}))
 assert.deepEqual(failed,{db:true,state:true,manifest:false})
 assert.equal(errors.length,0,errors.join('\n'))
 assert.deepEqual(await fs.readFile(path.join(sourcePath,'journal.db')),original,'Source remains untouched')
 console.log('PASS: actual schema, paper migration, reset, invalid references, file:// UI, undo, invalid JSON, offline SQLite, export roundtrip, Atlas desktop LibraryStorage.open/loadSnapshot, attachment bytes, source unchanged')
}finally{await browser.close()}
