export const lessons = [
  {
    id: 'orientation',
    number: '00',
    kind: 'main',
    group: '主线',
    navLabel: '认识 Atlas',
    title: '认识 Atlas',
    eyebrow: '先建立正确的预期',
    objective: 'Atlas 记录的是你的决策证据，而不是替你判断行情。',
    description: '先用一分钟理解 Atlas 的边界，再开始第一笔记录。',
    tags: ['本地优先', '桌面工作台', '事实优先'],
    steps: [
      {
        id: 'observe',
        type: 'observe',
        eyebrow: '01 / 04 · 观察',
        title: '先看清 Atlas 的工作边界',
        body: [
          'Atlas 把交易前的计划、交易中的事实和交易后的复盘放在同一条记录里。它不替代行情软件，也不把一个盈亏数字当成全部答案。',
          '你会在一个本地教学数据里完成这条链路，所有示例都只用于理解工具。',
        ],
        facts: ['记录过程，而不是追求漂亮结果', '先捕捉，后整理', '用复盘把一次动作变成下一次可执行的改进'],
        demo: 'atlas-shell',
        productView: 'journal',
        actionLabel: '开始练习',
      },
      {
        id: 'operate',
        type: 'operate',
        eyebrow: '02 / 04 · 操作',
        title: '选择你想改善的事情',
        body: ['教学的起点不是记住所有按钮，而是先明确你希望 Atlas 帮你看见什么。'],
        prompt: '如果只能先解决一个问题，你会选哪一个？',
        action: 'intent',
        options: [
          { value: 'process', label: '改进交易过程', hint: '看见计划、执行和复盘之间的断点' },
          { value: 'memory', label: '记住高价值案例', hint: '把值得回看的交易沉淀下来' },
          { value: 'risk', label: '守住风险边界', hint: '让风险证据和数据维护可追溯' },
        ],
        success: '很好。Atlas 的价值来自持续记录与回看，而不是一次性填完一张表。',
        actionLabel: '选择一个方向',
      },
      {
        id: 'understand',
        type: 'understand',
        eyebrow: '03 / 04 · 理解',
        title: '你会在三种层次之间移动',
        body: ['一笔交易在 Atlas 里不是一个孤立的数字，而是一组可以回到来源的证据。'],
        demo: 'flow',
        takeaways: ['交易事实：发生了什么', '复盘判断：你怎样解释它', '案例沉淀：以后怎样再次找到它'],
        actionLabel: '我明白了',
      },
      {
        id: 'confirm',
        type: 'quiz',
        eyebrow: '04 / 04 · 确认',
        title: '确认你的第一条判断',
        question: '刚开始使用 Atlas 时，最重要的第一步是什么？',
        options: [
          { value: 'fill-every-field', label: '把所有字段一次填满' },
          { value: 'record-evidence', label: '先记录关键事实，之后再补充', correct: true },
          { value: 'watch-dashboard', label: '先看统计图表再决定是否记录' },
        ],
        explanation: '正确。Atlas 的记录流程允许先捕捉，再整理；这会降低开始记录的摩擦。',
        actionLabel: '完成入门判断',
      },
    ],
  },
  {
    id: 'record-first-trade',
    number: '01',
    kind: 'main',
    group: '主线',
    navLabel: '记录第一笔交易',
    title: '记录第一笔交易',
    eyebrow: '从事实开始',
    objective: '先记录品种、方向、状态和策略，给后面的复盘留下可靠起点。',
    description: '创建记录时只做必要选择，其他内容留到详情阶段。',
    tags: ['交易日志', '进行中', '策略'],
    steps: [
      {
        id: 'observe',
        type: 'observe',
        eyebrow: '01 / 04 · 观察',
        title: '交易日志先回答四个事实问题',
        body: ['你现在看到的是一条还没有完成的教学记录。它先确认“是什么、往哪边、处于什么状态、属于哪套策略”。'],
        facts: ['品种：BTCUSDT', '方向：做多', '状态：计划中', '策略：QA 自动化'],
        demo: 'record-list',
        actionLabel: '开始填写记录',
      },
      {
        id: 'operate',
        type: 'operate',
        eyebrow: '02 / 04 · 操作',
        title: '把交易事实放进记录',
        body: ['依次选择四个基础字段。这里不要求你现在写结论，也不会因为字段暂时为空而阻止开始。'],
        prompt: '完成下面四项，观察记录状态如何变得可追踪。',
        action: 'recordFields',
        actionLabel: '完成基础记录',
      },
      {
        id: 'understand',
        type: 'understand',
        eyebrow: '03 / 04 · 理解',
        title: '创建记录不等于完成复盘',
        body: ['记录建立后，你仍然可以在详情里补充截图、市场叙事、心理状态和复盘正文。状态“计划中”只是说明它还在工作流里。'],
        demo: 'record-state',
        takeaways: ['创建是捕捉入口', '状态表达工作流位置', '盈亏结果不能替代复盘内容'],
        actionLabel: '我明白了',
      },
      {
        id: 'confirm',
        type: 'quiz',
        eyebrow: '04 / 04 · 确认',
        title: '确认记录顺序',
        question: '为什么创建记录时不要求一次填完所有复盘字段？',
        options: [
          { value: 'avoid-data', label: '因为那些字段不会被保存' },
          { value: 'reduce-friction', label: '因为先捕捉事实，再整理能降低记录摩擦', correct: true },
          { value: 'only-profit', label: '因为 Atlas 只关心最终盈亏' },
        ],
        explanation: '正确。Atlas 把捕捉与整理分开，让你先保住现场证据，再在盘后完成理解。',
        actionLabel: '完成本节',
      },
    ],
  },
  {
    id: 'enrich-trade',
    number: '02',
    kind: 'main',
    group: '主线',
    navLabel: '补充详情',
    title: '补充详情',
    eyebrow: '把事实变成证据',
    objective: '用正文、截图和属性说明“当时发生了什么”，而不是只留下一个结果。',
    description: '详情页把正文阅读和属性检查分开，让你可以按需要逐步补充。',
    tags: ['详情', '截图', '属性区'],
    steps: [
      {
        id: 'observe',
        type: 'observe',
        eyebrow: '01 / 04 · 观察',
        title: '详情页把正文和属性放在不同角色里',
        body: ['中央正文适合记录盘面摘要、市场叙事和复盘判断；右侧属性区适合确认状态、方向、交易数据、标签和策略。'],
        facts: ['正文负责叙述与判断', '属性负责稳定事实', '截图保留当时看到的证据', '来源关系连接记录与案例'],
        demo: 'detail-panel',
        productView: 'detail',
        actionLabel: '打开详情练习',
      },
      {
        id: 'operate',
        type: 'operate',
        eyebrow: '02 / 04 · 操作',
        title: '打开属性，再补一条现场摘要',
        body: ['先展开属性区，再写下一句只描述事实的摘要，最后打开补充信息。动作顺序对应真实盘后整理流程。'],
        prompt: '完成三个动作：展开属性区、填写摘要、打开补充信息。',
        action: 'detailFields',
        actionLabel: '完成详情整理',
      },
      {
        id: 'understand',
        type: 'understand',
        eyebrow: '03 / 04 · 理解',
        title: '字段不是越多越好，而是各自负责一件事',
        body: ['当你把事实、判断、截图和标签分开，之后的搜索、筛选、案例沉淀和统计才有稳定的依据。'],
        demo: 'detail-roles',
        takeaways: ['摘要描述看到的事实', '复盘正文解释你的判断', '标签帮助找到同类问题', '截图保留当时的视觉证据'],
        actionLabel: '我明白了',
      },
      {
        id: 'confirm',
        type: 'quiz',
        eyebrow: '04 / 04 · 确认',
        title: '确认详情页的分工',
        question: '哪一项最适合放在稳定属性区，而不是复盘正文里？',
        options: [
          { value: 'market-story', label: '你如何理解市场叙事' },
          { value: 'status-direction', label: '交易状态与方向', correct: true },
          { value: 'next-action', label: '下一次要怎样改进' },
        ],
        explanation: '正确。状态与方向是稳定属性；判断与改进动作应该留在正文里展开。',
        actionLabel: '完成本节',
      },
    ],
  },
  {
    id: 'complete-review',
    number: '03',
    kind: 'main',
    group: '主线',
    navLabel: '完成复盘',
    title: '完成复盘',
    eyebrow: '让记录产生下一步',
    objective: '用一个事实和一个改进动作结束这条复盘，而不是只给交易贴上“赢 / 亏”的标签。',
    description: '完成复盘是工作流状态，不是对交易好坏的道德评价。',
    tags: ['复盘状态', '错误 / 违规', '改进动作'],
    steps: [
      {
        id: 'observe',
        type: 'observe',
        eyebrow: '01 / 04 · 观察',
        title: '完成复盘要留下两个可回看的句子',
        body: ['第一句写事实：我当时做了什么、看见了什么。第二句写改进：下次遇到相同条件，我要提前做什么。'],
        facts: ['事实不等于自我评价', '改进动作要能在下一次执行', '复盘状态与盈亏语义分开'],
        demo: 'review-editor',
        actionLabel: '开始写复盘',
      },
      {
        id: 'operate',
        type: 'operate',
        eyebrow: '02 / 04 · 操作',
        title: '写下事实和下一次动作',
        body: ['教学数据只需要两句。写完后点击完成复盘，观察顶栏状态从待处理变成已复盘。'],
        prompt: '先写事实，再写下一次的具体动作。',
        action: 'reviewFields',
        actionLabel: '完成复盘',
      },
      {
        id: 'understand',
        type: 'understand',
        eyebrow: '03 / 04 · 理解',
        title: '“已复盘”不是“这笔交易正确”',
        body: ['它只说明这条记录已经被处理，并留下了可以再次检查的证据。你可以在后续随机复盘里重新审视它。'],
        demo: 'review-state',
        takeaways: ['状态回答“处理到哪一步”', '结果回答“发生了什么”', '改进动作回答“下次怎么做”'],
        actionLabel: '我明白了',
        toolLink: { href: '/guide/composer/', label: '起草一段复盘正文' },
      },
      {
        id: 'confirm',
        type: 'quiz',
        eyebrow: '04 / 04 · 确认',
        title: '确认复盘状态的含义',
        question: '点击“完成复盘”后，最准确的理解是什么？',
        options: [
          { value: 'approved-trade', label: 'Atlas 判定这笔交易是正确的' },
          { value: 'processed', label: '这条记录已经留下可回看的复盘证据', correct: true },
          { value: 'added-profit', label: '这笔交易一定会计入盈利统计' },
        ],
        explanation: '正确。复盘完成是工作流状态，不改变交易结果，也不代替统计口径。',
        actionLabel: '完成本节',
      },
    ],
  },
  {
    id: 'case-library',
    number: '04',
    kind: 'main',
    group: '主线',
    navLabel: '沉淀案例',
    title: '沉淀案例',
    eyebrow: '把高价值内容留下来',
    objective: '把值得反复查看的交易从日志中沉淀为可检索、可追溯的案例。',
    description: '案例不是复制一份正文，而是保留与原始交易的来源关系。',
    tags: ['案例库', '来源关系', '可追溯'],
    steps: [
      {
        id: 'observe',
        type: 'observe',
        eyebrow: '01 / 04 · 观察',
        title: '案例库负责长期回看',
        body: ['日志适合捕捉和筛选，案例库适合保存那些以后还会用来对照、教学或提醒自己的内容。'],
        facts: ['案例保留来源关系', '案例正文可以被再次整理', '日志与案例不是两套互相孤立的事实'],
        demo: 'case-link',
        actionLabel: '开始案例练习',
      },
      {
        id: 'operate',
        type: 'operate',
        eyebrow: '02 / 04 · 操作',
        title: '把教学交易加入案例库',
        body: ['先加入案例，再打开来源关系。右侧会显示它来自哪条交易记录。'],
        prompt: '完成“加入案例库”和“查看来源关系”两个动作。',
        action: 'caseLink',
        actionLabel: '完成案例沉淀',
      },
      {
        id: 'understand',
        type: 'understand',
        eyebrow: '03 / 04 · 理解',
        title: '案例的价值在于下一次还能找到它',
        body: ['当你按策略、错误标签、市场情境或来源关系回看时，案例会成为稳定的对照材料。'],
        demo: 'case-roles',
        takeaways: ['日志承接日常数量', '案例承接长期价值', '来源关系保证内容可以回到事实'],
        actionLabel: '我明白了',
      },
      {
        id: 'confirm',
        type: 'quiz',
        eyebrow: '04 / 04 · 确认',
        title: '确认案例与日志的关系',
        question: '为什么案例需要保留原始交易来源？',
        options: [
          { value: 'duplicate', label: '为了让同一笔交易在统计里出现两次' },
          { value: 'trace', label: '为了从长期总结回到原始事实和上下文', correct: true },
          { value: 'hide', label: '为了隐藏原始记录里的不完整字段' },
        ],
        explanation: '正确。案例是长期回看的入口，但可信度来自它仍然能回到原始事实。',
        actionLabel: '完成本节',
      },
    ],
  },
  {
    id: 'read-statistics',
    number: '05',
    kind: 'main',
    group: '主线',
    navLabel: '读懂统计',
    title: '读懂统计',
    eyebrow: '先看范围，再看数字',
    objective: '统计的第一步不是找最高的数字，而是确认这些数字来自哪一组记录。',
    description: '切换范围，观察同一指标为什么会变化。',
    tags: ['统计分析', '数据范围', '口径'],
    steps: [
      {
        id: 'observe',
        type: 'observe',
        eyebrow: '01 / 04 · 观察',
        title: '统计页面先交代当前数据范围',
        body: ['同一个胜率、盈亏或交易数量，在实盘、模拟盘、全部记录和错过机会范围下，含义完全不同。'],
        facts: ['范围决定哪些记录进入计算', '错过机会用于复盘判断，不代表实盘亏损', '教学数字只用于演示口径变化'],
        demo: 'stats-range',
        productView: 'stats',
        actionLabel: '开始看统计',
      },
      {
        id: 'operate',
        type: 'operate',
        eyebrow: '02 / 04 · 操作',
        title: '切换统计范围',
        body: ['选择一个范围，再观察交易数量、胜率和结果旁的说明。先问“统计谁”，再问“数字多少”。'],
        prompt: '至少切换一次实盘、模拟盘或全部记录。',
        action: 'statsScope',
        actionLabel: '确认统计范围',
      },
      {
        id: 'understand',
        type: 'understand',
        eyebrow: '03 / 04 · 理解',
        title: '数字必须和口径一起阅读',
        body: ['当范围改变，数字变化不代表工具出错；它可能只是代表你正在观察另一组记录。'],
        demo: 'stats-reading',
        takeaways: ['数字是结论', '范围是前提', '说明文字是边界'],
        actionLabel: '我明白了',
      },
      {
        id: 'confirm',
        type: 'quiz',
        eyebrow: '04 / 04 · 确认',
        title: '确认统计阅读顺序',
        question: '看到一个很高的胜率时，你应该先检查什么？',
        options: [
          { value: 'color', label: '先看它是不是绿色' },
          { value: 'range', label: '先看数据范围、记录类型和时间边界', correct: true },
          { value: 'compare', label: '先和别人的胜率比较' },
        ],
        explanation: '正确。统计先要可解释，再谈比较；数据范围是解释的起点。',
        actionLabel: '完成本节',
      },
    ],
  },
  {
    id: 'review-loop',
    number: '06',
    kind: 'main',
    group: '主线',
    navLabel: '周复盘与随机复盘',
    title: '周复盘与随机复盘',
    eyebrow: '从记录回到行为',
    objective: '周期复盘看一段时间里的模式，随机复盘检查你是否仍然理解过去的决策。',
    description: '这两个入口不是重复写日志，而是把旧记录重新变成反馈。',
    tags: ['周期复盘', '随机复盘', '掌握度'],
    steps: [
      {
        id: 'observe',
        type: 'observe',
        eyebrow: '01 / 04 · 观察',
        title: '两个入口解决两个不同问题',
        body: ['周复盘从时间范围出发，适合归纳本周反复出现的模式；随机复盘从一条旧交易出发，适合检查自己还能否说清当时的证据。'],
        facts: ['周复盘：从多条记录看模式', '随机复盘：从一条记录查记忆', '掌握度评估会决定下一次复习节奏'],
        productView: 'period',
        actionLabel: '开始复盘练习',
      },
      {
        id: 'operate',
        type: 'operate',
        eyebrow: '02 / 04 · 操作',
        title: '给一条旧交易做掌握度评估',
        body: ['先回忆这条交易为什么进入案例库，再选择你目前的掌握程度。评估不是给自己打分，而是安排下一次回看。'],
        prompt: '选择一个评估结果。',
        action: 'reviewRating',
        actionLabel: '完成掌握度评估',
      },
      {
        id: 'understand',
        type: 'understand',
        eyebrow: '03 / 04 · 理解',
        title: '复盘是反馈环，不是一次性总结',
        body: ['当你在周复盘里看到模式，在随机复盘里重新解释单笔交易，记录才会从“过去发生过”变成“下次可以使用”。'],
        demo: 'review-loop',
        takeaways: ['周期复盘归纳模式', '随机复盘检查理解', '掌握度决定下一次回看'],
        actionLabel: '我明白了',
      },
      {
        id: 'confirm',
        type: 'quiz',
        eyebrow: '04 / 04 · 确认',
        title: '确认两个复盘入口的区别',
        question: '哪一种任务最适合放进随机复盘？',
        options: [
          { value: 'weekly-summary', label: '总结本周所有交易的共同模式' },
          { value: 'single-memory', label: '重新解释一条旧交易，并判断自己是否掌握', correct: true },
          { value: 'backup', label: '导出完整数据库备份' },
        ],
        explanation: '正确。随机复盘围绕单条旧交易运行，周复盘则围绕一段时间的模式。',
        actionLabel: '完成本节',
      },
    ],
  },
  {
    id: 'special-records',
    number: '07',
    kind: 'branch',
    group: '分支',
    navLabel: '其它记录方式',
    title: '其它记录方式',
    eyebrow: '选择正确的来源',
    objective: '实盘、模拟盘、错过机会、随记和今日工作台各自适合不同的捕捉场景。',
    description: '先判断你正在记录哪一种事情，再看它是否进入哪类统计。',
    tags: ['模拟盘', '错过机会', '随记', '今日工作台'],
    steps: [
      {
        id: 'observe',
        type: 'observe',
        eyebrow: '01 / 04 · 观察',
        title: '不同入口不是同一类记录',
        body: ['“我执行了一笔交易”“我看见了但没有执行”“我想先记下一个想法”是三种不同的事情。正确来源会让后续统计和复盘不被混淆。'],
        facts: ['模拟盘：独立练习', '错过机会：复盘判断，不计入实盘绩效', '随记：快速捕捉，不等同于交易记录', '今日工作台：按当天任务组织记录'],
        demo: 'source-compare',
        productView: 'journal',
        actionLabel: '开始来源练习',
      },
      {
        id: 'operate',
        type: 'operate',
        eyebrow: '02 / 04 · 操作',
        title: '为场景选择正确来源',
        body: ['选一个你正在记录的场景，观察它的统计归属说明。'],
        prompt: '选择一个来源类型。',
        action: 'sourceMapping',
        actionLabel: '确认来源理解',
      },
      {
        id: 'understand',
        type: 'understand',
        eyebrow: '03 / 04 · 理解',
        title: '来源决定“以后在哪里看见它”',
        body: ['选择来源不是给记录贴标签，而是决定它在交易日志、统计分析、周复盘和案例流程里的位置。'],
        demo: 'source-rule',
        takeaways: ['实盘进入实盘统计', '模拟盘保持独立', '错过机会用于判断，不替代亏损', '随记先保留想法'],
        actionLabel: '我明白了',
      },
      {
        id: 'confirm',
        type: 'quiz',
        eyebrow: '04 / 04 · 确认',
        title: '确认错过机会的统计边界',
        question: '错过机会最准确的定位是什么？',
        options: [
          { value: 'loss', label: '一笔还没有平仓的亏损交易' },
          { value: 'review-signal', label: '用于复盘判断，但不计入实盘绩效', correct: true },
          { value: 'paper', label: '一笔模拟盘交易' },
        ],
        explanation: '正确。错过机会保留“当时看见了什么”的证据，但它不是实盘盈亏。',
        actionLabel: '完成本节',
      },
    ],
  },
  {
    id: 'risk-maintenance',
    number: '08',
    kind: 'branch',
    group: '分支',
    navLabel: '风险与维护',
    title: '风险与维护',
    eyebrow: '保护长期数据',
    objective: '风险证据和数据维护让你知道当前状态，也知道在出问题时如何恢复。',
    description: '这里的重点不是制造紧张，而是把影响、范围和恢复路径说清楚。',
    tags: ['风险管理', '数据', '回收站', '恢复'],
    steps: [
      {
        id: 'observe',
        type: 'observe',
        eyebrow: '01 / 04 · 观察',
        title: '维护入口保护的是证据连续性',
        body: ['风险页面关注准备、限制和证据；数据页面关注备份、导入、重复检测、恢复和回收站。它们共同保护你长期积累的记录。'],
        facts: ['风险提示陈述事实，不替你决策', '完整备份包含交易、正文、截图和设置', '恢复与删除操作必须明确后果'],
        demo: 'risk-maintenance',
        productView: 'data',
        actionLabel: '开始维护练习',
      },
      {
        id: 'operate',
        type: 'operate',
        eyebrow: '02 / 04 · 操作',
        title: '选择一个维护动作',
        body: ['选择你要处理的维护场景，再阅读它的影响范围。教学站不会真的导出或恢复任何文件。'],
        prompt: '选择一个你会优先理解的维护动作。',
        action: 'maintenanceChoice',
        actionLabel: '确认维护理解',
      },
      {
        id: 'understand',
        type: 'understand',
        eyebrow: '03 / 04 · 理解',
        title: '数据维护不是“设置页的附属项”',
        body: ['当记录里有正文、截图、案例来源和风险证据时，备份与恢复就是复盘系统的一部分，而不是最后才想起的清理工作。'],
        demo: 'maintenance-rule',
        takeaways: ['先确认影响范围', '完整备份优先保住附件与来源', '恢复前说明会覆盖什么', '风险修复要保留证据链'],
        actionLabel: '我明白了',
      },
      {
        id: 'confirm',
        type: 'quiz',
        eyebrow: '04 / 04 · 确认',
        title: '确认完整备份的作用',
        question: '如果你希望连同正文、截图和来源关系一起保留，优先选择哪一种？',
        options: [
          { value: 'json', label: '只下载结构化 JSON 副本' },
          { value: 'journal', label: '导出完整备份', correct: true },
          { value: 'trash', label: '把记录移到回收站' },
        ],
        explanation: '正确。完整备份面向整个资料库和附件；JSON 副本的范围更窄，需要按说明使用。',
        actionLabel: '完成本节',
      },
    ],
  },
  {
    id: 'settings-efficiency',
    number: '09',
    kind: 'branch',
    group: '分支',
    navLabel: '设置与桌面效率',
    title: '设置与桌面效率',
    eyebrow: '让工作流稳定下来',
    objective: '策略、标签、品种、模板、显示、快捷键和更新把重复动作变得可预期。',
    description: '最后认识桌面效率入口，让 Atlas 更贴合你的长期记录习惯。',
    tags: ['快捷键', '策略', '标签', '显示', '更新'],
    steps: [
      {
        id: 'observe',
        type: 'observe',
        eyebrow: '01 / 04 · 观察',
        title: '设置是工作流的底层秩序',
        body: ['策略和标签让内容可筛选，模板和品种减少重复输入，显示设置调整密度，快捷键与命令面板减少鼠标往返。'],
        facts: ['Windows 使用 Ctrl 修饰键', 'macOS 使用 Command 修饰键', '设置改变工作流，不改变历史事实'],
        demo: 'settings-shortcuts',
        actionLabel: '开始效率练习',
      },
      {
        id: 'operate',
        type: 'operate',
        eyebrow: '02 / 04 · 操作',
        title: '切换平台并打开命令面板',
        body: ['选择你的桌面平台，再点击命令面板示例。快捷键提示会随平台同步变化。'],
        prompt: '先选择 Windows 或 macOS，再打开命令面板。',
        action: 'shortcutPractice',
        actionLabel: '确认效率练习',
      },
      {
        id: 'understand',
        type: 'understand',
        eyebrow: '03 / 04 · 理解',
        title: '一致的入口会降低认知负担',
        body: ['当同一个动作在导航、快捷键、命令面板和按钮中保持同一个名字，你就不需要重新猜测每个页面的规则。'],
        demo: 'settings-rule',
        takeaways: ['名称稳定', '快捷键可发现', '显示设置只改变呈现', '更新入口说明版本变化'],
        actionLabel: '我明白了',
      },
      {
        id: 'confirm',
        type: 'quiz',
        eyebrow: '04 / 04 · 确认',
        title: '完成 Atlas 入门路径',
        question: '当你想快速开始一条高频操作时，最适合先找哪里？',
        options: [
          { value: 'random', label: '随机点击侧栏，直到找到入口' },
          { value: 'command', label: '命令面板或对应的桌面快捷键', correct: true },
          { value: 'settings-only', label: '每次都重新配置一次设置' },
        ],
        explanation: '正确。命令面板与快捷键把高频动作集中起来，适合长期桌面工作流。',
        actionLabel: '完成全部教学',
      },
    ],
  },
];

lessons.splice(4,0,{
 id:'quick-notes',number:'04',kind:'main',group:'主线',navLabel:'随记与反思',title:'随记与反思',eyebrow:'把尚未成形的想法留下来',objective:'记录盘面观察、情绪与纪律，在回看中理解自己的判断。',description:'打开侧栏随记，新建内容后填写标题与正文；用置顶和搜索找回重要记录。',tags:['随记','反思','交易纪律'],
 steps:[
 {id:'observe',type:'observe',eyebrow:'01 / 04 · 观察',title:'不必等到成交，才开始记录',body:['盘中闪过的判断、错过机会时的情绪、想反复提醒自己的纪律，都可以先放进随记。','随记提供标题、正文、置顶与搜索。它保存思考，不会把一段文字当成一笔成交或计入交易统计。'],facts:['即时记录观察与反思','置顶需要反复提醒自己的内容','用搜索和列表回到过去的判断'],productView:'notes',actionLabel:'开始练习'},
 {id:'operate',type:'operate',eyebrow:'02 / 04 · 操作',title:'为一条想法选择合适的位置',body:['Yunkoo 今天没有成交，但发现自己因为担心错过而反复看盘，想把这段感受留给盘后回看。'],prompt:'请选择适合保存这条观察的记录方式。',action:'sourceMapping',success:'随记可以保留没有成交的观察；已有执行事实时，应使用对应的交易记录。',actionLabel:'完成分类'},
 {id:'understand',type:'understand',eyebrow:'03 / 04 · 理解',title:'回看随记，让感受变得具体',body:['给记录一个以后能搜到的标题，写清发生的情境、当时的判断，以及下一次想验证的事情。重要的纪律可以置顶。','复盘时回看这些观察，分清“看见了什么”和“怎样解释它”。需要形成下一周承诺时，再进入周期复盘整理。'],demo:'source-rule',actionLabel:'我明白了'},
 {id:'confirm',type:'quiz',eyebrow:'04 / 04 · 确认',title:'确认随记的作用',question:'没有成交，但想记录盘中情绪和观察，应该怎样处理？',options:[{value:'note',label:'写入随记，保留上下文并在之后回看',correct:true},{value:'trade',label:'创建一笔虚构成交，让它进入盈亏统计'},{value:'skip',label:'没有成交，所以不需要留下任何记录'}],explanation:'正确。随记保存思考，交易日志保存执行事实，两者共同支持复盘。',actionLabel:'完成随记学习'}
 ]
});
lessons.forEach((lesson,index)=>{lesson.number=String(index).padStart(2,'0');});

export const lessonGroups = [
  { id: 'main', label: '核心工作流' },
  { id: 'branch', label: '进阶与维护' },
];
