import fs from 'node:fs/promises'
import path from 'node:path'
import {
  assertUnique,
  parseOfficialCategories,
  parseSymbols,
  renderStaticComponent,
  sha256,
  toComponentName,
  toRegistryName,
} from './core.mjs'

const root = path.resolve('assets/linear-icon-system')
const sourceDir = path.join(root, 'raw')
const outputDir = path.resolve('src/icons/linear/static')
const generatedPath = path.resolve('src/icons/linear/generated.ts')
const spriteFiles = ['svg-1.svg', 'svg-2.svg', 'svg-3.svg']

const symbols = (
  await Promise.all(
    spriteFiles.map(async (file) =>
      parseSymbols(await fs.readFile(path.join(sourceDir, file), 'utf8'), file),
    ),
  )
).flat()

const unique = new Map()
const duplicates = []
for (const symbol of symbols) {
  if (unique.has(symbol.linearName)) duplicates.push(symbol.linearName)
  else unique.set(symbol.linearName, symbol)
}

const categorySource = await fs.readFile(
  path.join(sourceDir, 'modules/EmojiContainer.CeAZEvLX.js'),
  'utf8',
)
const categories = parseOfficialCategories(categorySource)

const officialTechnologyFallbacks = new Set([
  'AiWriting',
  'Alarm',
  'AlarmDelete',
  'Anonymous',
  'BarGraph',
  'Biscuit',
  'ChatLine',
  'Circle',
  'Clock',
  'Clock--outline',
  'EmptyCircle',
  'ExclamationMark',
  'Flag',
  'GooglePlay',
  'LinearAi',
  'QuestionMark',
  'Ramp',
  'Report',
  'Resolved',
  'ResolvedChat',
  'ScatterPlot',
  'SmallLock',
  'SoundMuted',
  'Starred',
  'Stopwatch',
])

const records = [...unique.values()]
  .map((symbol) => {
    const mappedCategory = categories.get(symbol.linearName)
    const usesOfficialFallback = officialTechnologyFallbacks.has(symbol.linearName)
    const category = mappedCategory ?? (usesOfficialFallback ? 'technology' : undefined)
    if (!category) throw new Error(`Unreviewed category fallback: ${symbol.linearName}`)
    const name = toRegistryName(symbol.linearName)
    const componentName = toComponentName(symbol.linearName)
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${symbol.viewBox}">${symbol.body}</svg>\n`
    return {
      ...symbol,
      name,
      componentName,
      category,
      categorySource: mappedCategory ? 'official-map' : 'official-technology-fallback',
      rendering: 'static',
      defaultSize: 16,
      sha256: sha256(svg),
      svg,
    }
  })
  .sort((a, b) => a.name.localeCompare(b.name))

assertUnique(records, 'name')
assertUnique(records, 'componentName')
if (records.length !== 301) throw new Error(`Expected 301 icons, received ${records.length}`)

await fs.rm(outputDir, { recursive: true, force: true })
await fs.mkdir(outputDir, { recursive: true })
await fs.rm(path.join(root, 'categories'), { recursive: true, force: true })

for (const record of records) {
  await fs.writeFile(
    path.join(outputDir, `${record.componentName}.tsx`),
    renderStaticComponent(record),
    'utf8',
  )
  const categoryDir = path.join(root, 'categories', record.category)
  await fs.mkdir(categoryDir, { recursive: true })
  await fs.writeFile(path.join(categoryDir, `${record.linearName}.svg`), record.svg, 'utf8')
}

const indexLines = [
  '// Generated by scripts/linear-icons/generate.mjs; do not edit.',
  ...records.map((record) => `export { ${record.componentName} } from './${record.componentName}'`),
  '',
]
await fs.writeFile(path.join(outputDir, 'index.ts'), indexLines.join('\n'), 'utf8')

const nameUnion = records.map((record) => `  | '${record.name}'`).join('\n')
const categorySet = [...new Set(records.map((record) => record.category))].sort()
const categoryUnion = categorySet.map((category) => `  | '${category}'`).join('\n')

const metadataEntries = records
  .map((record) => {
    const meta = {
      name: record.name,
      linearName: record.linearName,
      componentName: record.componentName,
      category: record.category,
      categorySource: record.categorySource,
      rendering: record.rendering,
      defaultSize: record.defaultSize,
      viewBox: record.viewBox,
      source: record.source,
      sha256: record.sha256,
    }
    return `  '${record.name}': ${JSON.stringify(meta)} as const`
  })
  .join(',\n')

const staticIconImports = records
  .map((record) => `import { ${record.componentName} } from './static/${record.componentName}'`)
  .join('\n')

const staticIconEntries = records
  .map((record) => `  '${record.name}': ${record.componentName}`)
  .join(',\n')

const generated = `// Generated by scripts/linear-icons/generate.mjs; do not edit.
import type { ComponentType } from 'react'
import type { LinearStaticIconProps } from './types'
${staticIconImports}

export type LinearIconName =
${nameUnion}

export type LinearIconCategory =
${categoryUnion}

export const linearIconMetadata = {
${metadataEntries},
} as const

export const linearStaticIcons = {
${staticIconEntries},
} as const satisfies Record<LinearIconName, ComponentType<LinearStaticIconProps>>
`

await fs.writeFile(generatedPath, generated, 'utf8')

const manifestRecords = records.map(({ body, svg, ...record }) => record)
await fs.writeFile(
  path.join(root, 'manifest.json'),
  `${JSON.stringify({ count: records.length, duplicates, icons: manifestRecords }, null, 2)}\n`,
  'utf8',
)

const galleryData = `window.LINEAR_ICON_MANIFEST = ${JSON.stringify({
  count: records.length,
  duplicates,
  icons: manifestRecords,
})};\n`
await fs.writeFile(path.join(root, 'gallery-data.js'), galleryData, 'utf8')

console.log(`Generated ${records.length} Linear static icons`)
